local keyofday = require("willette-scripts.keyofday")

describe("keyofday", function()
  it("should return the key of the day", function()
    local current_time = os.date("*t")
    local start_of_day = os.time(current_time)
    local key = keyofday.keyofday(start_of_day)
    vim.print(key)
  end)
end)
